package media.tiger.tigerbox.p016ui.common;

import kotlin.Metadata;
import kotlin.jvm.internal.DefaultConstructorMarker;
import media.tiger.tigerbox.C2814R;

@Metadata(mo33736d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0000\n\u0002\u0018\u0002\n\u0002\b&\b\u0001\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u0001B\u000f\b\u0002\u0012\u0006\u0010\u0002\u001a\u00020\u0003¢\u0006\u0002\u0010\u0004R\u0011\u0010\u0002\u001a\u00020\u0003¢\u0006\b\n\u0000\u001a\u0004\b\u0005\u0010\u0006j\u0002\b\u0007j\u0002\b\bj\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(¨\u0006)"}, mo33737d2 = {"Lmedia/tiger/tigerbox/ui/common/InfoDialogType;", "", "infoDialog", "Lmedia/tiger/tigerbox/ui/common/InfoDialog;", "(Ljava/lang/String;ILmedia/tiger/tigerbox/ui/common/InfoDialog;)V", "getInfoDialog", "()Lmedia/tiger/tigerbox/ui/common/InfoDialog;", "WRONG_PASSWORD", "WIFI_CONNECTION_FAILED", "INTERNET_CONNECTION_FAILED", "INTERNET_CONNECTION_FAILED_SINGLE_BUTTON", "ACCESS_FAILURE", "NFC_READ_ERROR", "CARD_NOT_FOUND", "WILDCARD_UNPROCESSED", "WILDCARD_PRIVATE", "EXPIRED_CARD", "ENTRY_BLOCKED", "GENERAL_ERROR", "PREMIUM_ACCESS_READY", "WILDCARD_ASSIGN_ERROR", "TIGERTICKET_403_ERROR", "TIGERTICKET_404_ERROR", "TIGERTICKET_410_ERROR", "TIGERTICKET_429_ERROR", "TIGERTICKET_REDEEM", "PARENTAL_GATE_WRONG_CUSTOM_PIN", "PARENTAL_GATE_WRONG_RANDOM_PIN", "DELETE_ALL_DOWNLOADS", "DELETE_PROFILE_DOWNLOADS", "DELETE_ALL_CONFIRMATION", "TIME_LIMIT_RESET_OR_ADJUST", "NO_WIRELESS_SIGNAL", "FIRST_SYNC_WARNING", "SECOND_SYNC_WARNING", "FINAL_SYNC_WARNING", "ERROR_SAFEGUARD_HARDWARE_900", "PRODUCT_LIST_ERROR", "SWIPE_INDICATOR_WIFI", "SWIPE_INDICATOR_GEAR", "FIRMWARE_ERROR", "app_tigerBoxRelease"}, mo33738k = 1, mo33739mv = {1, 6, 0}, mo33741xi = 48)
/* renamed from: media.tiger.tigerbox.ui.common.InfoDialogType */
/* compiled from: InfoDialogType.kt */
public enum InfoDialogType {
    WRONG_PASSWORD(new InfoDialog(C2814R.C2816drawable.vector_error_700_wrong_password, C2814R.string.error_700_headline, C2814R.string.error_700_text, C2814R.string.dialog_error_message_new_password_text, InfoDialogTypeResult.RETRY_PASSWORD, C2814R.string.dialog_error_message_cancel_button_text, (InfoDialogTypeResult) null, false, false, 0, false, 1984, (DefaultConstructorMarker) null)),
    WIFI_CONNECTION_FAILED(new InfoDialog(C2814R.C2816drawable.vector_error_701_connection_with_a_new_wifi_failed, C2814R.string.error_701_headline, C2814R.string.error_701_text, C2814R.string.dialog_error_message_try_again, InfoDialogTypeResult.RETRY_CONNECTION, C2814R.string.dialog_error_message_cancel_button_text, (InfoDialogTypeResult) null, false, false, 0, false, 1984, (DefaultConstructorMarker) null)),
    INTERNET_CONNECTION_FAILED(new InfoDialog(C2814R.C2816drawable.vector_error_703_connection_with_internet_failed, C2814R.string.error_703_headline, C2814R.string.error_703_text, C2814R.string.dialog_error_message_try_again, InfoDialogTypeResult.RETRY_CONNECTION, C2814R.string.dialog_error_message_cancel_button_text, (InfoDialogTypeResult) null, false, false, 0, false, 1984, (DefaultConstructorMarker) null)),
    INTERNET_CONNECTION_FAILED_SINGLE_BUTTON(new InfoDialog(C2814R.C2816drawable.vector_error_703_connection_with_internet_failed, C2814R.string.error_703_headline, C2814R.string.error_703_text, C2814R.string.dialog_error_message_ok_button_text, InfoDialogTypeResult.NO_INTERNET_ERROR, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2016, (DefaultConstructorMarker) null)),
    ACCESS_FAILURE(new InfoDialog(C2814R.C2816drawable.vector_error_410_music_treble_clef, C2814R.string.error_410_headline, C2814R.string.error_410_text, C2814R.string.dialog_error_message_ok_button_text, InfoDialogTypeResult.PRODUCT_ACQUISITION_ERROR, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2016, (DefaultConstructorMarker) null)),
    NFC_READ_ERROR(new InfoDialog(C2814R.C2816drawable.error_dialog_nfc, C2814R.string.error_nfc_card_read_title, C2814R.string.error_nfc_card_read_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    CARD_NOT_FOUND(new InfoDialog(C2814R.C2816drawable.error_dialog_wildcard_invalid, C2814R.string.error_wildcard_not_valid_title, C2814R.string.error_wildcard_not_valid_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    WILDCARD_UNPROCESSED(new InfoDialog(C2814R.C2816drawable.error_dialog_wildcard_unprocessed, C2814R.string.error_nfc_card_unprocessed_title, C2814R.string.error_nfc_card_unprocessed_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    WILDCARD_PRIVATE(new InfoDialog(C2814R.C2816drawable.error_dialog_wildcard_private, C2814R.string.error_nfc_card_private_title, C2814R.string.error_nfc_card_private_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    EXPIRED_CARD(new InfoDialog(C2814R.mipmap.ticket_warning, C2814R.string.error_nfc_card_expired_title, C2814R.string.error_nfc_card_expired_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    ENTRY_BLOCKED(new InfoDialog(C2814R.C2816drawable.vector_header_close, C2814R.string.error_nfc_card_entry_blocked_title, C2814R.plurals.error_nfc_card_entry_blocked_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, -1, (InfoDialogTypeResult) null, true, false, 0, false, 1280, (DefaultConstructorMarker) null)),
    GENERAL_ERROR(new InfoDialog(C2814R.C2816drawable.vector_error, C2814R.string.error_nfc_card_general_title, C2814R.string.error_nfc_card_general_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    PREMIUM_ACCESS_READY(new InfoDialog(C2814R.C2816drawable.dialog_success_nfc_premium_access, -1, C2814R.string.success_premium_access_nfc_card_message, C2814R.string.success_premium_access_nfc_card_button, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    WILDCARD_ASSIGN_ERROR(new InfoDialog(C2814R.C2816drawable.error_dialog_assign_wildcard, C2814R.string.error_nfc_card_assign_title, C2814R.string.error_nfc_card_assign_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    TIGERTICKET_403_ERROR(new InfoDialog(C2814R.C2816drawable.vector_error, C2814R.string.error_nfc_tigerticket_403_title, C2814R.string.error_nfc_tigerticket_403_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    TIGERTICKET_404_ERROR(new InfoDialog(C2814R.C2816drawable.vector_error, C2814R.string.error_nfc_tigerticket_404_title, C2814R.string.error_nfc_tigerticket_404_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    TIGERTICKET_410_ERROR(new InfoDialog(C2814R.mipmap.ticket_warning, C2814R.string.error_nfc_card_expired_title, C2814R.string.error_nfc_card_expired_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    TIGERTICKET_429_ERROR(new InfoDialog(C2814R.C2816drawable.vector_error, C2814R.string.error_nfc_tigerticket_429_title, C2814R.string.error_nfc_tigerticket_429_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, -1, (InfoDialogTypeResult) null, true, false, 1, false, 1280, (DefaultConstructorMarker) null)),
    TIGERTICKET_REDEEM(new InfoDialog(-1, C2814R.string.nfc_tigerticket_redeem_confirmation_title, C2814R.string.nfc_tigerticket_redeem_confirmation_message, C2814R.string.nfc_tigerticket_redeem_right_text, InfoDialogTypeResult.TIGER_TICKET_REDEEM_CONFIRMED, C2814R.string.nfc_tigerticket_redeem_left_text, InfoDialogTypeResult.TIGER_TICKET_REDEEM_CANCELED, true, false, 0, false, 1792, (DefaultConstructorMarker) null)),
    PARENTAL_GATE_WRONG_CUSTOM_PIN(new InfoDialog(C2814R.C2816drawable.tigerbox_lock_closed_red, C2814R.string.dialog_parental_gate_wrong_custom_pin_title, C2814R.string.dialog_parental_gate_wrong_custom_pin_message, C2814R.string.dialog_parental_gate_wrong_pin_button, (InfoDialogTypeResult) null, -1, (InfoDialogTypeResult) null, false, false, 0, false, 512, (DefaultConstructorMarker) null)),
    PARENTAL_GATE_WRONG_RANDOM_PIN(new InfoDialog(C2814R.C2816drawable.tigerbox_lock_closed_red, C2814R.string.dialog_parental_gate_wrong_random_pin_title, C2814R.string.dialog_parental_gate_wrong_random_pin_message, C2814R.string.dialog_parental_gate_wrong_pin_button, (InfoDialogTypeResult) null, -1, (InfoDialogTypeResult) null, false, false, 0, false, 512, (DefaultConstructorMarker) null)),
    DELETE_ALL_DOWNLOADS(new InfoDialog(-1, C2814R.string.dialog_delete_all_downloads_title, C2814R.string.dialog_delete_all_downloads_message, C2814R.string.dialog_delete_all_downloads_positive_button, InfoDialogTypeResult.DELETE_DOWNLOADS_CONFIRMED, C2814R.string.dialog_error_message_cancel_button_text, (InfoDialogTypeResult) null, false, false, 0, false, 1984, (DefaultConstructorMarker) null)),
    DELETE_PROFILE_DOWNLOADS(new InfoDialog(-1, C2814R.string.dialog_delete_profile_downloads_title, C2814R.string.dialog_delete_profile_downloads_message, C2814R.string.dialog_delete_profile_downloads_right_button, InfoDialogTypeResult.DELETE_DOWNLOADS_CONFIRMED, C2814R.string.dialog_delete_profile_downloads_left_button, InfoDialogTypeResult.DELETE_PROFILE_DOWNLOADS_CONFIRMED, true, true, 0, false, 512, (DefaultConstructorMarker) null)),
    DELETE_ALL_CONFIRMATION(new InfoDialog(-1, C2814R.string.dialog_delete_all_downloads_confirmation_title, C2814R.string.dialog_delete_all_downloads_confirmation_message, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    TIME_LIMIT_RESET_OR_ADJUST(new InfoDialog(-1, C2814R.string.dialog_time_limit_reset_or_adjust_title, C2814R.string.dialog_time_limit_reset_or_adjust_message, C2814R.string.dialog_time_limit_adjust_button, InfoDialogTypeResult.TIME_LIMIT_ADJUST, C2814R.string.dialog_time_limit_reset_button, InfoDialogTypeResult.TIME_LIMIT_RESET, false, false, 0, false, 1920, (DefaultConstructorMarker) null)),
    NO_WIRELESS_SIGNAL(new InfoDialog(C2814R.C2816drawable.error_dialog_no_wifi_signal, C2814R.string.error_no_wlan_signal_title, C2814R.string.error_no_wlan_signal_message, C2814R.string.error_no_wlan_signal_positive_button, InfoDialogTypeResult.SELECT_WIFI_NETWORKS, C2814R.string.dialog_error_message_cancel_button_text, (InfoDialogTypeResult) null, false, false, 0, false, 1984, (DefaultConstructorMarker) null)),
    FIRST_SYNC_WARNING(new InfoDialog(C2814R.C2816drawable.error_dialog_sync_first_warning, C2814R.string.error_offline_warning_title, C2814R.string.error_offline_first_warning_message, C2814R.string.error_offline_warning_positive_button, InfoDialogTypeResult.CONFIRM_SYNC, C2814R.string.error_offline_warning_negative_button, (InfoDialogTypeResult) null, false, false, 0, false, 1984, (DefaultConstructorMarker) null)),
    SECOND_SYNC_WARNING(new InfoDialog(C2814R.C2816drawable.error_dialog_sync_second_warning, C2814R.string.error_offline_warning_title, C2814R.string.error_offline_second_warning_message, C2814R.string.error_offline_warning_positive_button, InfoDialogTypeResult.CONFIRM_SYNC, C2814R.string.error_offline_warning_negative_button, (InfoDialogTypeResult) null, false, false, 0, false, 1984, (DefaultConstructorMarker) null)),
    FINAL_SYNC_WARNING(new InfoDialog(C2814R.C2816drawable.error_dialog_sync_second_warning, C2814R.string.error_offline_warning_title, C2814R.string.error_offline_final_warning_message, C2814R.string.error_offline_warning_positive_button, InfoDialogTypeResult.CONFIRM_SYNC_FINAL, C2814R.string.error_offline_warning_negative_button, (InfoDialogTypeResult) null, false, false, 0, false, 1984, (DefaultConstructorMarker) null)),
    ERROR_SAFEGUARD_HARDWARE_900(new InfoDialog(C2814R.C2816drawable.error_900_hardware, C2814R.string.error_900_headline, C2814R.string.error_900_text, 0, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2040, (DefaultConstructorMarker) null)),
    PRODUCT_LIST_ERROR(new InfoDialog(C2814R.C2816drawable.error_dialog_product_list_error, C2814R.string.error_product_list_title, C2814R.string.error_product_list_message, C2814R.string.dialog_error_message_ok_button_text, InfoDialogTypeResult.PRODUCT_LIST_ERROR, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2016, (DefaultConstructorMarker) null)),
    SWIPE_INDICATOR_WIFI(new InfoDialog(-2, C2814R.string.open_parental_settings_dialog_title, C2814R.string.open_parental_settings_dialog_text_wifi, C2814R.string.ota_not_available_button, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    SWIPE_INDICATOR_GEAR(new InfoDialog(-2, C2814R.string.open_parental_settings_dialog_title, C2814R.string.open_parental_settings_dialog_text_gear, C2814R.string.ota_not_available_button, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null)),
    FIRMWARE_ERROR(new InfoDialog(C2814R.C2816drawable.error_dialog_firmware, C2814R.string.error_dialog_firmware_dialog_title, C2814R.string.error_dialog_firmware_dialog_text, C2814R.string.dialog_error_message_ok_button_text, (InfoDialogTypeResult) null, 0, (InfoDialogTypeResult) null, false, false, 0, false, 2032, (DefaultConstructorMarker) null));
    
    private final InfoDialog infoDialog;

    private InfoDialogType(InfoDialog infoDialog2) {
        this.infoDialog = infoDialog2;
    }

    public final InfoDialog getInfoDialog() {
        return this.infoDialog;
    }
}
