# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/language-java/
version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:

      # Download and cache dependencies

      - run:  echo Compiling and creating jar 
      - run:  git
      - run:  mkdir build && javac -d ./build ~/repo/*/*.java && javac -d ./build ~/repo/*.java && javac -d ./build ~/repo/*/*/*.java  || true
      - run:  cd build 
      - run:  jar cvf tigerboxApp.jar * || true
      - run:  copy tigerboxApp.jar /tmp/artifacts-tbt/tigerboxApp.jar

      - store_artifacts:
          path: /tmp/artifacts-tbt
          destination: tigerboxApp.jar


      